# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'c1b85bfc-6814-4c8f-b9a8-2f4fccfe6edf'

  # Web app name
  webAppName: 'rdblogserver'

  # Environment name
  environmentName: 'test'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # mariadb root password
  mariadb_root_pwd = 'l55Wl06g121my7870g3z9092'
  # app db user
  app_db_user = 'appuser'
  # app db password
  app_db_pwd = 'ek470oJ05dj057465137lh00'
  # app db name
  app_db_name = 'blog_db'

stages:
- stage: setup_mariadb
  displayName: Setup MariaDB Database
  jobs:
  - job: InstallMariaDB
    displayName: Install MariaDB
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        yum -y install mariadb-server mariadb
        systemctl enable mariadb --now
        mysqladmin -u root password $(mariadb_root_pwd)
        cat <<EOT > /tmp/setup_app_db.sql
        create database blog_db;
        create user '$(app_db_user)'@localhost identified by '$(app_db_pwd)';
        grant all privileges on $(app_db_name).* to '$(app_db_user)'@localhost;
        flush privileges;
        EOT
        mysql -u root --password='$(mariadb_root_pwd)' < /tmp/setup_app_db.sql
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - script: |
        echo "Starting maven build .."
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: '
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
