# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'c1b85bfc-6814-4c8f-b9a8-2f4fccfe6edf'

  # Web app name
  webAppName: 'rdblogserver'

  # Environment name
  environmentName: 'test'

  # Agent VM image name
  vmImageName: 'centos-latest'

stages:
- stage: setup_mariadb
  displayName: Setup MariaDB Database
  jobs:
  - job: InstallMariaDB
    displayName: Install MariaDB
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        yum -y install mariadb-server mariadb
        systemctl enable mariadb --now
        mysqladmin -u root password $(MARIADB_ROOT_PWD)
        cat <<EOT > /tmp/setup_app_db.sql
        create database $(APP_DB_NAME);
        create user '$(APP_DB_USE)'@localhost identified by '$(APP_DB_PWD)';
        grant all privileges on $(APP_DB_NAME).* to '$(APP_DB_USER)'@localhost;
        flush privileges;
        EOT
        mysql -u root --password='$(MARIADB_ROOT_PWD)' < /tmp/setup_app_db.sql
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - script: |
        echo "Starting maven build .."
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: '
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
